# Generated by Django 4.0.4 on 2022-05-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_link_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Пользователь'),
        ),
    ]
