# Generated by Django 4.0.4 on 2022-05-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_link_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link1',
            field=models.CharField(max_length=250, verbose_name='Длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link2',
            field=models.CharField(max_length=50, unique=True, verbose_name='Сокращенная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
