# Generated by Django 4.0.4 on 2022-05-17 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_link_link1_alter_link_link2_alter_link_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created'], 'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AddField(
            model_name='link',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='link1',
            field=models.URLField(max_length=250, verbose_name='Длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='link2',
            field=models.CharField(max_length=250, unique=True, verbose_name='Сокращенная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
