# Generated by Django 4.0.4 on 2022-05-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_link_options_link_created_alter_link_link1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.RemoveField(
            model_name='link',
            name='created',
        ),
    ]
